# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'NopCommerce' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

pod 'Alamofire', '~> 4.0'
pod 'Kingfisher'
pod 'DropDown'
pod 'PayPal-iOS-SDK'
pod 'Firebase/Analytics'
pod 'Firebase/Crashlytics'

  # Pods for NopCommerce

end
